# resolver: lts-7.24
resolver: lts-11.8
# resolver: nightly-2018-05-10
extra-deps:
- git: https://github.com/chrisdone/hexml.git
  commit: 22923b55ca7390f1973ddfd0d0e517f13cf8a8a4
- hexpat-0.20.9
- List-0.5.2
- libxml-0.1.1
